---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: docker:dind
    privileged: true
    detach: true
    command: [ "dockerd", "--host=tcp://0.0.0.0:2375" ]

  - name: version
    image: alpine:3.13
    commands:
    - apk add --update --no-cache curl git jq
    - LATEST=$(curl -s https://api.github.com/repos/kiwiirc/kiwiirc/tags | jq -r '.[0].name')
    - if curl -sfL https://hub.docker.com/v2/repositories/ezkrg/kiwiirc/tags/$LATEST > /dev/null; then echo "tag $LATEST already exist"; exit 78; fi
    - echo -n "$LATEST" > .tag

  - name: build
    image: ezkrg/buildx:latest
    environment:
      USER:
        from_secret: DHU
      PASSWORD:
        from_secret: DHP
      DOCKER_HOST: tcp://docker:2375
    commands:
    - sleep 5
    - TAG=$(cat .tag)
    - docker buildx create --use --name docker --node docker --platform linux/amd64 --driver docker-container $DOCKER_HOST
    - echo $PASSWORD | docker login --username $USER --password-stdin
    - docker buildx build --load --cache-from ezkrg/cache:kiwiirc --cache-to ezkrg/cache:kiwiirc -t ezkrg/kiwiirc:$TAG --build-arg VERSION=$TAGs .
    - docker push ezkrg/kiwiirc:$TAG
    - docker tag ezkrg/kiwiirc:$TAG ezkrg/kiwiirc:latest
    - docker push ezkrg/kiwiirc:latest
---
kind: signature
hmac: b28061a1e8e2fda2b99338c5f74e081c97795609c37b5052ec62887040f4befd

...
